"""Finite reviewed ART25 claims; not natural-language inference."""

PROFILES = {
    "ICASE19-001": {
        "conclusion": "候補の確認を続ける。Huntの支持だけでIncidentを宣言しない。",
        "alternative": "未記録の正当な管理変更かもしれない。",
        "confidence": "低",
        "confidenceBasis": "供給Signalだけで追加の宣言判断はない。",
        "gap": "業務承認文脈が不足している。",
        "nextAction": "宣言基準に必要な確認事項を記録する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-002": {
        "conclusion": "供給された基準判定と所有者の記録に限ってDeclaredとする。実Incidentの宣言ではない。",
        "alternative": "誤設定や承認記録不足という説明を残す。",
        "confidence": "中",
        "confidenceBasis": "宣言記録はあるが、組織全体の影響は分からない。",
        "gap": "未観測Dataの影響はUnknownのままである。",
        "nextAction": "Evidence Questionと合成選択肢の比較へ進む。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-003": {
        "conclusion": "供給された対象と時点に限ってContainedとする。侵害の終結ではない。",
        "alternative": "別経路の影響が残る可能性がある。",
        "confidence": "中",
        "confidenceBasis": "事前保持と合成承認、限定した検証記録が揃う。",
        "gap": "未知の対象には封じ込め効果を拡張できない。",
        "nextAction": "調査継続と切戻し条件を別々に記録する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-004": {
        "conclusion": "Investigatingとして因果と影響を問う。攻撃者を確定しない。",
        "alternative": "正当な変更と誤設定も比較対象に残す。",
        "confidence": "低",
        "confidenceBasis": "分析対象は供給記録に限定される。",
        "gap": "Root causeと全影響はまだ確定していない。",
        "nextAction": "第20章向けEvidence Questionを未配達で記録する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-005": {
        "conclusion": "Recoveringへの条件は揃うが、復旧完了とはしない。",
        "alternative": "復旧条件の見落としが残る可能性がある。",
        "confidence": "中",
        "confidenceBasis": "入口の基準判定と担当者だけを供給した。",
        "gap": "サービス正常性の別検証が必要である。",
        "nextAction": "Validationと残余リスクの判定を計画する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-006": {
        "conclusion": "供給Scopeの復旧検証と残余リスクの担当を条件にClosedとする。改善完了ではない。",
        "alternative": "未観測範囲や再発要因が残る可能性がある。",
        "confidence": "中",
        "confidenceBasis": "限定した復旧結果と閉鎖判断を供給した。",
        "gap": "組織全体の安全と再発防止完了は未評価である。",
        "nextAction": "残余リスクと改善Backlogを別期限で追跡する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-007": {
        "conclusion": "閉鎖後に利用可能となった新しい供給EvidenceでReopenedとする。旧閉鎖記録を消さない。",
        "alternative": "新しい記録が既知事象の遅延情報かもしれない。",
        "confidence": "低",
        "confidenceBasis": "再開理由はあるが新情報の全影響は未分析である。",
        "gap": "新しいEvidenceの解釈を再検討する必要がある。",
        "nextAction": "旧Decision IDを参照した新判断を追記する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-008": {
        "conclusion": "宣言根拠が不足するためSuspectedを維持する。",
        "alternative": "Event不足で判断材料が揃っていない。",
        "confidence": "低",
        "confidenceBasis": "Huntの支持を追加の宣言基準に代用できない。",
        "gap": "判断主体と供給基準の確認が必要である。",
        "nextAction": "不足根拠のOwnerと次回確認を記録する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-009": {
        "conclusion": "正当変更という代替が残り、基準は未確定のためSuspectedを維持する。",
        "alternative": "誤設定の可能性も残す。",
        "confidence": "低",
        "confidenceBasis": "部分的な承認文脈だけでは宣言基準を満たさない。",
        "gap": "正当変更の対象と時点の追加確認が必要である。",
        "nextAction": "承認の不足を照会する計画だけを記録する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-010": {
        "conclusion": "Log不足をUnknownとして残し、Suspectedを維持する。侵害なしとはしない。",
        "alternative": "未観測の影響も無害な変更もあり得る。",
        "confidence": "低",
        "confidenceBasis": "供給Scopeの一部が未観測である。",
        "gap": "未知の範囲を除外範囲に置換できない。",
        "nextAction": "Collection gapとEvidence Questionを渡す計画を記録する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-011": {
        "conclusion": "選択肢の記録だけではContainedに進めず、Declaredを維持する。",
        "alternative": "Monitoringだけでは拡大が続く可能性がある。",
        "confidence": "低",
        "confidenceBasis": "封じ込め効果を示す供給検証がない。",
        "gap": "実行済みとも効果確認済みともいえない。",
        "nextAction": "効果の検証条件を再設計する計画を記録する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
    "ICASE19-012": {
        "conclusion": "復旧検証が未確定のためRecoveringを維持する。Closedとしない。",
        "alternative": "限定した正常性確認が不足している。",
        "confidence": "低",
        "confidenceBasis": "入口基準だけでは復旧完了を示せない。",
        "gap": "復旧後の完全性と正常性の確認が必要である。",
        "nextAction": "復旧検証と残余リスクの見直しを記録する。",
        "reassessment": "対象、版、Scope、供給Evidence、承認、正常性、残余リスクが変わったら別Decisionで再評価する。",
    },
}
